name: upsidedown
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - swig
  - altair=3.2.0=py37_0
  - python=3.7.3
  - pip=19.3.1
  - pytorch
  - torchvision 
  - cpuonly
  - jupyterlab=1.1.4
  - ipywidgets=7.5.1
  - nodejs=10.13.0
  - pyglet
  - pip:
    - sacred
    - gym==0.15.4
    - Box2D
    - matplotlib==3.1.1
    - tensorflow-datasets==1.3.0
    - tensorflow==2.0.0
    - tensorflow-probability
    - plac
    - atari-py